use git's --grep option
This also adds colored logs to make sure people's attention is redirected to the error easily

diff --git a/.github/workflows/block-fixup-commits.yaml b/.github/workflows/block-fixup-commits.yaml
--- a/.github/workflows/block-fixup-commits.yaml
+++ b/.github/workflows/block-fixup-commits.yaml
@@ -3,6 +3,11 @@ name: Block "fixup" commit merges
 on:
   workflow_call:
 
+env:
+  RED: '\033[0;31m'
+  YELLOW: '\033[0;33m'
+
+
 jobs:
   check-commits:
     runs-on: ubuntu-latest
@@ -20,11 +25,13 @@ jobs:
     - name: Look for the fixup prefix
       id: search-for-fixup-prefix
       run: |
-        commit_messages=$(git log origin/${{ github.event.pull_request.base.ref }}..fork/${{ github.event.pull_request.head.ref }} --format=%B)
-        fixup_commits=$(echo "$commit_messages" | grep "^fixup" || true)
-        if [ -n "$fixup_commits" ]; then
-            echo "Please make sure that all commits that have the 'fixup' prefix need to be squashed before merging."
-            echo "Commits with 'fixup' prefix:"
-            echo "$fixup_commits"
+        commit_messages=$(git log origin/${{ github.event.pull_request.base.ref }}..fork/${{ github.event.pull_request.head.ref }} --format="%h %B" --grep "^fixup" --oneline)
+        if [ -n "commit_messages" ]; then
+            echo -e "$RED Error: Make sure that all 'fixup' prefixed commits are squashed before merging."
+            echo -e "$RED Commits that need fixing:"
+            while IFS= read -r line; do
+              echo -e "$YELLOW${line}"
+            done <<< "$commit_messages"
+            exit 1
             exit 1
         fi
